package repo

import (
	"database/sql"
	"fmt"
	"log"
)

// DBAdapter abstracts database differences between SQLite, DM (达梦), and KingBase (金仓).
type DBAdapter interface {
	// Open opens a connection to the database.
	Open(dsn string) (*sql.DB, error)
	// Placeholder returns the placeholder style for parameterized queries.
	Placeholder(index int) string
	// Upsert returns an INSERT ... ON CONFLICT statement.
	Upsert(table string, columns []string, conflict string) string
	// NowExpr returns the SQL expression for current timestamp.
	NowExpr() string
	// BoolType returns the SQL type for boolean fields.
	BoolType() string
	// AutoIncrement returns the SQL for auto-increment primary key.
	AutoIncrement() string
	// DriverName returns the database driver name.
	DriverName() string
}

// SQLiteAdapter implements DBAdapter for SQLite.
type SQLiteAdapter struct{}

func (a *SQLiteAdapter) Open(dsn string) (*sql.DB, error) {
	db, err := sql.Open("sqlite3", dsn+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	db.SetConnMaxLifetime(0)
	return db, nil
}

func (a *SQLiteAdapter) Placeholder(index int) string { return "?" }
func (a *SQLiteAdapter) Upsert(table string, columns []string, conflict string) string {
	return fmt.Sprintf("INSERT OR REPLACE INTO %s", table)
}
func (a *SQLiteAdapter) NowExpr() string    { return "datetime('now')" }
func (a *SQLiteAdapter) BoolType() string   { return "INTEGER" }
func (a *SQLiteAdapter) AutoIncrement() string { return "INTEGER PRIMARY KEY AUTOINCREMENT" }
func (a *SQLiteAdapter) DriverName() string { return "sqlite3" }

// DMAdapter implements DBAdapter for 达梦 (DM Database).
type DMAdapter struct{}

func (a *DMAdapter) Open(dsn string) (*sql.DB, error) {
	// DM uses its own driver: dm8 or gdbc
	// For now, log a warning and fall back
	log.Printf("WARNING: DM database adapter is a stub. DSN: %s", dsn)
	return nil, fmt.Errorf("DM database driver not installed — install dm8 driver")
}

func (a *DMAdapter) Placeholder(index int) string { return fmt.Sprintf(":%d", index) }
func (a *DMAdapter) Upsert(table string, columns []string, conflict string) string {
	return fmt.Sprintf("MERGE INTO %s", table)
}
func (a *DMAdapter) NowExpr() string    { return "SYSDATE" }
func (a *DMAdapter) BoolType() string   { return "NUMBER(1)" }
func (a *DMAdapter) AutoIncrement() string { return "NUMBER GENERATED BY DEFAULT AS IDENTITY" }
func (a *DMAdapter) DriverName() string { return "dm" }

// KingBaseAdapter implements DBAdapter for 金仓 (KingBase ES).
type KingBaseAdapter struct{}

func (a *KingBaseAdapter) Open(dsn string) (*sql.DB, error) {
	// KingBase uses PostgreSQL wire protocol
	log.Printf("WARNING: KingBase database adapter is a stub. DSN: %s", dsn)
	return nil, fmt.Errorf("KingBase database driver not installed — install kingbase driver")
}

func (a *KingBaseAdapter) Placeholder(index int) string { return fmt.Sprintf("$%d", index) }
func (a *KingBaseAdapter) Upsert(table string, columns []string, conflict string) string {
	return fmt.Sprintf("INSERT INTO %s ON CONFLICT %s", table, conflict)
}
func (a *KingBaseAdapter) NowExpr() string    { return "NOW()" }
func (a *KingBaseAdapter) BoolType() string   { return "BOOLEAN" }
func (a *KingBaseAdapter) AutoIncrement() string { return "BIGSERIAL PRIMARY KEY" }
func (a *KingBaseAdapter) DriverName() string { return "kingbase" }

// GetDBAdapter returns the appropriate adapter for the given driver name.
func GetDBAdapter(driver string) DBAdapter {
	switch driver {
	case "dm", "dameng":
		return &DMAdapter{}
	case "kingbase", "kb":
		return &KingBaseAdapter{}
	default:
		return &SQLiteAdapter{}
	}
}

// NewDBWithAdapter opens a database using the appropriate adapter.
func NewDBWithAdapter(driver, dsn string) (*sql.DB, DBAdapter, error) {
	adapter := GetDBAdapter(driver)
	db, err := adapter.Open(dsn)
	if err != nil {
		return nil, nil, err
	}
	return db, adapter, nil
}
